from code.visualisations import visualize
from code.classes.amino import Amino
from code.classes.protein import Protein
from code.algorithms.help_methods.timer import Timer
from code.algorithms.greedy import BestGreedy
from code.algorithms.random import BestOfRandom
from code.algorithms.hill_climber import HillClimber
from code.algorithms.simulated_annealing import SimulatedAnnealing
from code.algorithms.bfs_plus import BFSPlus
from code.algorithms.bfs_plus_3d import BFSPlus3D
from code.algorithms.thomas_protein_folder import BBProteinFolder